import java.awt.Color;
import java.awt.*;
import javax.swing.JScrollPane;  
import javax.swing.*;
public class Menulayout extends javax.swing.JFrame {

    /**
     * Creates new form Menulayout
     */
    public Menulayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        citylist1 = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        emailtf1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mobiletf1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        male1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        regis1 = new javax.swing.JLabel();
        firstnametf1 = new javax.swing.JTextField();
        lastnametf1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        labelSubmit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204,204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION FORM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Frutiger LT Std 55 Roman", 1, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        jLabel9.setText("CITY");

        citylist1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Banglore", "Mangalore", "Trichy", "Coimbatore" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(citylist1);

        jLabel14.setText("EMAIL");

        emailtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtf1ActionPerformed(evt);
            }
        });

        jLabel19.setText("MOBILE NUMBER");

        mobiletf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobiletf1KeyTyped(evt);
            }
        });

        jLabel20.setText("GENDER");

        male1.setBackground(new java.awt.Color(204, 204, 255));
        male1.setSelected(true);
        male1.setText("MALE");
        male1.setActionCommand("");
        male1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male1ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 255));
        jRadioButton3.setText("FEMALE");

        jLabel21.setText("ADDRESS");

        username1.setText("FIRST NAME");

        regis1.setText("LAST NAME");

        firstnametf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametf1ActionPerformed(evt);
            }
        });
        firstnametf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnametf1KeyTyped(evt);
            }
        });

        lastnametf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnametf1KeyTyped(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        submit.setBackground(new java.awt.Color(153, 153, 255));
        submit.setText("Submit");
        submit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                submitMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                submitMouseMoved(evt);
            }
        });
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(153, 153, 255));
        clear.setText("Exit");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        clear1.setBackground(new java.awt.Color(153, 153, 255));
        clear1.setText("Clear");
        clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clear1MouseExited(evt);
            }
        });
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username1)
                    .addComponent(regis1)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstnametf1)
                    .addComponent(mobiletf1)
                    .addComponent(emailtf1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(male1)
                                .addGap(27, 27, 27)
                                .addComponent(jRadioButton3))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lastnametf1))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clear1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username1)
                    .addComponent(firstnametf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regis1)
                    .addComponent(lastnametf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobiletf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male1)
                    .addComponent(jLabel20)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel21)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSubmit.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu2.setText("Layout");
        jMenu2.setToolTipText("");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("BorderLayout");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("FlowLayout");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("GridLayout");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("CardLayout");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem4);

        jRadioButtonMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("GridBagLayout");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem5);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(labelSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
public static CardLayout card = new CardLayout();

    private void emailtf1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void mobiletf1KeyTyped(java.awt.event.KeyEvent evt) {                                   
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {evt.consume();}

        if(mobiletf1.getText().length()>=10)
        {evt.consume();}        // TODO add your handling code here:
    }                                  

    private void male1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void firstnametf1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void firstnametf1KeyTyped(java.awt.event.KeyEvent evt) {                                      
        char enter = evt.getKeyChar();
        if(!(Character.isLetter(enter)))
        {
            evt.consume();
        }
    }                                     

    private void lastnametf1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        char enter = evt.getKeyChar();
        if(!(Character.isLetter(enter)))
        {evt.consume();}
    }                                    

    private void submitMouseDragged(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void submitMouseMoved(java.awt.event.MouseEvent evt) {                                  

    }                                 

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        submit.setBackground(new Color(26, 117, 255));
        submit.setForeground(Color.WHITE);
    }                                   

    private void submitMouseExited(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        submit.setBackground(new Color(153,153,255));
        submit.setForeground(Color.BLACK);
    }                                  

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(firstnametf1.getText().equals("") || lastnametf1.getText().equals("") || emailtf1.getText().equals("") || mobiletf1.getText().equals("")||jTextArea1.getText().equals("")|| citylist1.isSelectionEmpty()==true)
        {
            labelSubmit.setText("Incomplete Personal Details!");
            
        }
        else
        { 
            labelSubmit.setText("Registered!!");
           
        }
           card.next(jPanel1);
        //        if(!(mobiletf.getText().matches("^[0-9]{1,3}$"))
    }                                      

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        clear.setBackground(new Color(26, 117, 255));
        clear.setForeground(Color.WHITE);
    }                                  

    private void clearMouseExited(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        clear.setBackground(new Color(153,153,255));
        clear.setForeground(Color.BLACK);
    }                                 

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {                                      
        card.next(jPanel1);
        System.exit(0);
    }                                     

    private void clear1MouseEntered(java.awt.event.MouseEvent evt) {                                    
        clear1.setBackground(new Color(26, 117, 255));
        clear1.setForeground(Color.WHITE);
    }                                   

    private void clear1MouseExited(java.awt.event.MouseEvent evt) {                                   
        clear1.setBackground(new Color(153,153,255));
        clear1.setForeground(Color.BLACK);
    }                                  

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        firstnametf1.setText("");
        lastnametf1.setText("");
        emailtf1.setText("");
        mobiletf1.setText("");
        citylist1.setSelectedIndex(0);
        jTextArea1.setText("");
    card.next(jPanel1);
        
    }                                      

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
      jPanel3.removeAll();
      jPanel3.revalidate();
      jPanel1.removeAll();
      this.remove(jPanel3);
      this.add(jPanel3);
      jPanel1.removeAll();
      jPanel3.setLayout(new BorderLayout());
      jPanel3.add(firstnametf1,BorderLayout.NORTH);  
      jPanel3.add(lastnametf1,BorderLayout.SOUTH);  
      jPanel3.add(emailtf1,BorderLayout.EAST);  
      jPanel3.add(mobiletf1,BorderLayout.WEST);  
      jPanel3.add(citylist1,BorderLayout.CENTER);
      jPanel3.add(jTextArea1,BorderLayout.NORTH);
      jPanel3.add(submit,BorderLayout.SOUTH);
      jPanel3.add(clear,BorderLayout.EAST);
      jPanel3.add(clear1,BorderLayout.WEST);
      jPanel3.setSize(565, 503);
      jPanel3.revalidate();
    }                                                     

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
      jPanel3.removeAll();
      jPanel3.revalidate();
      this.remove(jPanel3);
      this.add(jPanel3);
      
      jPanel3.add(firstnametf1);  
      jPanel3.add(firstnametf1);  
      jPanel3.add(lastnametf1);  
      jPanel3.add(emailtf1);  
      jPanel3.add(mobiletf1);  
      jPanel3.add(citylist1);
      jPanel3.add(jTextArea1);
      jPanel3.add(submit);
      jPanel3.add(clear);
      jPanel3.add(clear1);
      jPanel3.setLayout(new FlowLayout(FlowLayout.LEFT,10,20));
      jPanel3.setSize(565, 503);
      jPanel3.revalidate();
    }                                                     

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       jPanel3.removeAll();
      jPanel3.revalidate();
      this.remove(jPanel3);
      this.add(jPanel3);
      jPanel1.removeAll();
      jPanel3.setLayout(new GridLayout(3,3));
      jPanel3.add(firstnametf1);  
      jPanel3.add(lastnametf1);  
      jPanel3.add(emailtf1);  
      jPanel3.add(mobiletf1);  
      jPanel3.add(citylist1);
      jPanel3.add(jTextArea1);
      jPanel3.add(submit);
      jPanel3.add(clear);
      jPanel3.add(clear1);
      jPanel3.setSize(565, 503);
      jPanel3.revalidate();
    }                                                     

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
      jPanel3.removeAll();
      jPanel3.revalidate();
      jPanel1.removeAll();
      jPanel3.add(firstnametf1);  
      jPanel3.add(firstnametf1);  
      jPanel3.add(lastnametf1);  
      jPanel3.add(emailtf1);  
      jPanel3.add(mobiletf1);  
      jPanel3.add(citylist1);
      jPanel3.add(jTextArea1);
      jPanel3.add(submit);
      jPanel3.add(clear);
      jPanel3.add(clear1);
      setLayout(new BoxLayout (this, BoxLayout.X_AXIS));  
      jPanel3.setSize(565, 503);
      jPanel3.revalidate();
    }                                                     

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        jPanel1.removeAll();
        jPanel3.remove(clear);
        jPanel3.remove(submit);
        jPanel3.remove(clear1);
        jPanel3.revalidate();
        jPanel1.setLayout(card);
        jPanel1.add(submit);
        jPanel1.add(clear1);
        jPanel1.add(clear);
        jPanel1.revalidate();
        
    }                                                     

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                                      

      jPanel3.removeAll();
      jPanel1.removeAll();
      jPanel3.revalidate();
      this.remove(jPanel3);
      this.add(jPanel3);
      jPanel3.setLayout(new GridBagLayout());
      GridBagConstraints gb=new GridBagConstraints();
      gb.fill = GridBagConstraints.HORIZONTAL;
      gb.gridx = 0;
      gb.gridy = 0;
      jPanel3.add(firstnametf1,gb);
      jPanel3.add(firstnametf1,gb);  
      jPanel3.add(lastnametf1,gb);
      gb.gridx = 2;
      gb.gridy = 2;
      jPanel3.add(emailtf1,gb);  
      jPanel3.add(mobiletf1,gb);  
      jPanel3.add(citylist1,gb);
      jPanel3.add(jTextArea1,gb);
      gb.gridx = 0;
      gb.gridy = 0;
      jPanel3.add(submit,gb);
      jPanel3.add(clear,gb);
      jPanel3.add(clear1,gb);
      jPanel3.setSize(565, 503);
      jPanel3.revalidate();
    }                                                     

    private void jRadioButtonMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
    jPanel1.removeAll();
    
    }                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menulayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menulayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menulayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menulayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menulayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> citylist1;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear1;
    private javax.swing.JTextField emailtf1;
    private javax.swing.JTextField firstnametf1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelSubmit;
    private javax.swing.JTextField lastnametf1;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField mobiletf1;
    private javax.swing.JLabel regis1;
    private javax.swing.JButton submit;
    private javax.swing.JLabel username1;
    // End of variables declaration                   
}